version: "3.7"
name: todo

x-db-connection-environment: &db-connection-environment
  POSTGRES_USER: user_secret
  POSTGRES_PASSWORD: password_secret
  DB_HOST: db
  DB_PORT: 5432

x-debug-environment: &debug-environment
  SECRET_KEY: "l4y@!^rox=b*!x-qd9xa*nt%r$$zcp!p_d&1gh@b99s-#iqsj&"
  DEBUG: True

x-celery-environment: &celery-environment
  REDIS_URL: redis://redis:6379

services:
  db:
    image: postgres:12.11-bullseye
    volumes:
      - ./todo_database:/var/lib/postgresql
    environment:
      <<: *debug-environment
      <<: *db-connection-environment

  backend:
    image: sergio-giro/todo_backend
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/backend/
    environment:
      <<: *debug-environment
      <<: *db-connection-environment
      <<: *celery-environment
      WAIT_HOSTS: db:5432, redis:6379
    depends_on:
      - db

  redis:
    image: redis:7.0.4-bullseye

  celery:
    image: sergio-giro/todo_celery
    build:
      context: celery/
    environment:
      <<: *db-connection-environment
      <<: *celery-environment
      <<: *debug-environment
      WAIT_HOSTS: redis:6379
    working_dir: /backend
    volumes:
      - ./backend/:/backend/
    ports:
      - "6379:6379"
    entrypoint:
      celery -A backend worker
