# Generated by Django 4.2.13 on 2024-06-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="depiction",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
