# Generated by Django 4.2.13 on 2024-06-03 10:45

import todo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_depiction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="depiction",
            field=models.ImageField(
                null=True,
                storage=todo.models._select_storage,
                upload_to="1717411521.84833-eb55db9d-8f39-431e-93e9-e5534ee12cb4",
            ),
        ),
    ]
